/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ContactButtons() {
  return (
    <div className="flex gap-7 self-stretch my-auto text-sm font-medium tracking-tight text-center">
      <div className="flex flex-col justify-center p-px text-emerald-500 border border-emerald-500 border-solid">
        <button className="px-4 py-2.5 bg-white rounded-md">
          Área do Cliente
        </button>
      </div>
      <div className="flex flex-col self-start text-white">
        <button className="px-3.5 py-2.5 bg-emerald-500 rounded-md">
          Entre em contato
        </button>
      </div>
    </div>
  );
}

export default ContactButtons;
