/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex flex-wrap gap-5 justify-between p-10 max-w-full bg-emerald-500 w-[1680px] max-md:px-5 max-md:mr-1">
      <div className="text-xs font-medium leading-6 text-black">
        © 2024 Geo-SO. Todos os direitos reservados.
        <br />
        Desenvolvido por{" "}
      </div>
      <div className="flex flex-wrap gap-10 self-start max-md:max-w-full">
        <div className="flex gap-4 self-start text-xs font-medium leading-6 text-black">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b5ec5e6e29f71969851c49e4a3a6b5a4c9c867040d9405fb2e8fb3e093dad504?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8"
            alt="Phone icon"
            className="object-contain shrink-0 aspect-square w-[34px]"
          />
          <div>(11) 000-000-000</div>
        </div>
        <div className="flex gap-10 items-start">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/36d8aab91d8fc4107cc412d4154daea990f0777ca734f350bae8c8f89358b036?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8"
            alt="Social media icon 1"
            className="object-contain shrink-0 aspect-square w-[34px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ec8e9a9165a88a959fe0b2bd0e8cd8f54a54c55f7d9230c43f5787aa8695f3e6?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8"
            alt="Social media icon 2"
            className="object-contain shrink-0 aspect-square w-[34px]"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0cf38317076db72e6ab2502941b291475208bacd401fa2d6faad8df8c44910e8?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8"
            alt="Social media icon 3"
            className="object-contain shrink-0 aspect-square w-[35px]"
          />
        </div>
      </div>
    </footer>
  );
}

export default Footer;
