/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";
import ContactButtons from "./ContactButtons";

function Header() {
  return (
    <header className="flex gap-5 justify-between items-center py-4 pr-20 pl-9 max-w-full bg-white w-[1680px] max-md:px-5 max-md:mr-1">
      <Logo />
      <Navigation />
      <ContactButtons />
    </header>
  );
}

export default Header;
