/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/dfcc80b4dceea2000f67a28427ad18ad352bfb5c2c39f6daffdf9ed45eae87bd?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8"
      alt="Geo-SO Logo"
      className="object-contain shrink-0 self-stretch aspect-square w-[49px]"
    />
  );
}

export default Logo;
