/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import Services from "./Services";
import ServiceSearch from "./ServiceSearch";
import Footer from "./Footer";

function MainLayout() {
  return (
    <div className="flex flex-col">
      <Header />
      <main>
        <Hero />
        <Services />
        <ServiceSearch />
      </main>
      <Footer />
    </div>
  );
}

export default MainLayout;
