/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceCard from "./ServiceCard";

function Services() {
  const services = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/dca3c7214f570d7b332a35d90044a394dccb96721d29a313426a1765e51f1a8e?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8",
      title: "Varrição",
      description:
        "Consulte as sarjetas de ruas e calçadas em áreas de alto movimento de pedestres.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ca45d7a5b37f15cc8479baecf28b1529195b50d0db3ce3738d22ec2323cdcfe4?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8",
      title: "Cata-bagulho",
      description:
        "Consulte remoção de objetos volumosos descartados nas calçadas em dias e horários previamente agendados",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/be632f26f7670351d0b876b5d154ffadc5078fa12174a8cc9854e1cba7dd141a?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8",
      title: "Grandes corredores",
      description:
        "Consulte serviços completos de manutenção urbana em importantes avenidas.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/3a947e3a74016636f337bb844beaaf362f128c83c44bc1e4b4741da6957b6aab?placeholderIfAbsent=true&apiKey=50540d800e854c5199b8f44d34dba6f8",
      title: "Feiras",
      description:
        "Consulte a realização da limpeza, lavagem e o transporte de resíduos orgânicos para o destino adequado.",
    },
  ];

  return (
    <section className="flex overflow-hidden flex-col justify-center items-center px-20 py-28 -mt-2 bg-white max-md:px-5 max-md:py-24 max-md:mr-1 max-md:max-w-full">
      <div className="flex flex-col mb-0 w-full max-w-[1372px] max-md:mb-2.5 max-md:max-w-full">
        <div className="flex flex-wrap gap-10 items-start px-10 pb-32 w-full bg-white max-md:px-5 max-md:pb-24 max-md:max-w-full">
          {services.map((service, index) => (
            <ServiceCard key={index} {...service} />
          ))}
        </div>
        <button className="self-center px-14 py-4 mt-20 max-w-full text-lg font-medium tracking-tight text-center text-white bg-emerald-500 rounded-md w-[318px] max-md:px-5 max-md:mt-10">
          Conheça Nossos Serviços
        </button>
      </div>
    </section>
  );
}

export default Services;
